final:

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    front_right_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: front_left_wheel
        pid: {p: 100.0, i: 0.5, d: 0.1}

    front_left_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: front_right_wheel
        pid: {p: 100.0, i: 0.5, d: 0.1}

    back_right_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: back_left_wheel
        pid: {p: 100.0, i: 0.5, d: 0.1}

    back_left_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: back_right_wheel
        pid: {p: 100.0, i: 0.5, d: 0.1}

/final/gazebo_ros_control:
    pid_gains:
        front_left_wheel:
            p: 1.001
            i: 0.00
            d: 0.00
        front_right_wheel:
            p: 1.001
            i: 0.00
            d: 0.00
        back_left_wheel:
            p: 1.001
            i: 0.00
            d: 0.00
        back_right_wheel:
            p: 1.001
            i: 0.00
            d: 0.00
