brwheel_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: brwheel
  pid: { p: 1.0, i: 0.01, d: 0.0 }

blwheel_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: blwheel
  pid: { p: 1.0, i: 0.01, d: 0.0 }

frwheel_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: frwheel
  pid: { p: 1.0, i: 0.01, d: 0.0 }

flwheel_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: flwheel
  pid: { p: 1.0, i: 0.01, d: 0.0 }

